name: jenn-ci
run-name: ${{ github.actor }}-jenn-ci

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages/Release
permissions:
  contents: write  # IMPORTANT: mandatory for making GitHub Releases
  pages: write  
  id-token: write

on: 
  push:
    branches: 
      - '*'
    tags:        
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi and activate 'dev' environment
        uses: prefix-dev/setup-pixi@v0.9.1 # pinned version
        with:
          environments: dev # Specify the environment to install and activate

      - name: Run tests 
        run: pixi run -e dev --frozen test 

      - name: Check linting 
        run: pixi run -e dev --frozen lint 

      - name: â¬†ï¸ Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-py${{ matrix.python-version }}
          path: ./build
          overwrite: true

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi and activate 'dev' environment
        uses: prefix-dev/setup-pixi@v0.9.1 # pinned version
        with:
          environments: dev # Specify the environment to install and activate

      - name: Build docs using sphinx
        run: pixi run -e dev --frozen docs 

      - name: ðŸ’¾ Build distribution files
        shell: bash -el {0}
        run: | 
          pixi run -e dev --frozen build

      - name: â¬†ï¸ Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./build
          overwrite: true

  deploy: 
    needs: build 
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') # only release on tag pushes 
    steps: 
      - name: â¬‡ï¸ Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./build

      - name: Stage distribution for test release 
        shell: bash -el {0}
        run: | # GitHub Actions needs dist/ to be at root level
          mv ./build/dist .  

      - name: ðŸ“¦ Ship package to TestPyPI
        id: testpypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          skip-existing: true
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TESTPYPI_TOKEN }}

      - name: â¬†ï¸ Upload documentation to GitHub Pages
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload entire repository
          path: './build/docs/html'

      - name: ðŸ“° Publish Docs to GitHub Pages
        id: pypi
        uses: actions/deploy-pages@v4

      - name: ðŸ“¦ Ship package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          skip-existing: true
          repository-url: https://upload.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --notes ""

      - name: Upload artifact signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # Upload to GitHub Release using the `gh` CLI.
        # `dist/` contains the built packages, and the
        # sigstore-produced signatures and certificates.
        run: >-
          gh release upload
          '${{ github.ref_name }}' dist/**
          --repo '${{ github.repository }}'