name: jenn-ci
run-name: ${{ github.actor }}-jenn-ci

on: 
  push:
    branches: 
      - '*'
    tags:        
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi and activate 'dev' environment
        uses: prefix-dev/setup-pixi@v0.9.1 # pinned version
        with:
          environments: dev # Specify the environment to install and activate

      - name: Run tests 
        run: pixi run -e dev --frozen test 

      - name: Check linting 
        run: pixi run -e dev --frozen lint 

      - name: ‚¨ÜÔ∏è Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-py${{ matrix.python-version }}
          path: ./build
          overwrite: true

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi and activate 'dev' environment
        uses: prefix-dev/setup-pixi@v0.9.1 # pinned version
        with:
          environments: dev # Specify the environment to install and activate

      - name: Build docs using sphinx
        run: pixi run -e dev --frozen docs 

      - name: üíæ Build distribution files
        shell: bash -el {0}
        run: | 
          pixi run -e dev --frozen build

      - name: ‚¨ÜÔ∏è Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./build
          overwrite: true

    