name: jenn-ci
run-name: ${{ github.actor }}-jenn-ci

on: 
  push:
    branches: 
      - '*'
    tags:        
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi and activate 'dev' environment
        uses: prefix-dev/setup-pixi@v0.9.1 # pinned version
        with:
          environments: dev # Specify the environment to install and activate

      - name: Run tests 
        run: pixi run -e dev --frozen test 

      - name: Check linting 
        run: pixi run -e dev --frozen lint 

      - name: ⬆️ Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-py${{ matrix.python-version }}
          path: ./build
          overwrite: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixi and activate 'dev' environment
        uses: prefix-dev/setup-pixi@v0.9.1 # pinned version
        with:
          environments: dev # Specify the environment to install and activate

      - name: Build docs using sphinx
        run: pixi run -e dev --frozen docs 

    